PRIVATE_MESSAGE = {
    "sender_realm_str": "monadical",
    "content": "me 1 day",
    "sender_email": "juan@monadical.com",
    "sender_short_name": "juan",
    "recipient_id": 343,
    "subject_links": [],
    "id": 388205,
    "client": "website",
    "content_type": "text/x-markdown",
    "is_me_message": False,
    "subject": "",
    "type": "private",
    "display_recipient": [
        {
            "email": "juan@monadical.com",
            "short_name": "juan",
            "is_mirror_dummy": False,
            "full_name": "Juan",
            "id": 76,
        },
        {
            "email": "remindjd-bot@zulip.monadical.com",
            "short_name": "remindjd-bot",
            "is_mirror_dummy": False,
            "full_name": "RemindJD",
            "id": 165,
        },
    ],
    "avatar_url": "/user_avatars/4/e19b2cba5ab8a1dae719283f16885cc8dbed53ac.png?x=x&version=3",
    "timestamp": 1586895701,
    "sender_id": 76,
    "reactions": [],
    "sender_full_name": "Juan",
    "full_content": "me 1 day",
}
PUBLIC_MESSAGE = {
    "sender_realm_str": "monadical",
    "content": "me 1 day",
    "sender_email": "juan@monadical.com",
    "recipient_id": 98,
    "subject_links": [],
    "id": 388194,
    "client": "website",
    "content_type": "text/x-markdown",
    "stream_id": 25,
    "is_me_message": False,
    "subject": "reminder bot babble",
    "sender_short_name": "juan",
    "type": "stream",
    "display_recipient": "engineering",
    "avatar_url": "/user_avatars/4/e19b2cba5ab8a1dae719283f16885cc8dbed53ac.png?x=x&version=3",
    "timestamp": 1586895278,
    "sender_id": 76,
    "reactions": [],
    "sender_full_name": "Juan",
    "full_content": "@**RemindJD** me 1 day",
}
