# Generated by Django 3.0.5 on 2020-04-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindmoi_bot', '0003_auto_20200113_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
