# Generated by Django 3.0.5 on 2020-05-22 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('remindmoi_bot', '0005_oauthuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zulip_user_email', models.CharField(max_length=128)),
                ('dt_start', models.DateTimeField()),
            ],
        ),
    ]
